### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by Killian1967** [Lakatrazz/BONELAB-Fusion#108]
when I launch Bonelab and I get to the Melon Loader screen everything is fine until it reaches "Initializing Mod: LabFusion 1.8.0"
When it gets to that it freezes for about a second then just closes, I seem to be the only one with this issue because I've looked everywhere and haven't been able to find an answer as to how to fix this, I tried reinstalling melon loader but that didn't do anything 
![image](https://github.com/user-attachments/assets/f505a345-f6ef-4e82-b521-49a602a29b36)

**Comment by Lakatrazz** [comment]
Upload your Latest.log file (its in the MelonLoader folder next to your bonelab exe)

**Comment by Killian1967** [comment]
> Upload your Latest.log file (its in the MelonLoader folder next to your bonelab exe)

[18:51:21.646] ------------------------------
[18:51:21.669] MelonLoader v0.6.4 Open-Beta
[18:51:21.671] OS: Windows 11
[18:51:21.671] Hash Code: 57EE1B42E1FB9958A6BA7AB968E66098D05A9C82A5236075512B7E61BC7C2A65
[18:51:21.671] ------------------------------
[18:51:21.671] Game Type: Il2cpp
[18:51:21.672] Game Arch: x64
[18:51:21.672] ------------------------------
[18:51:21.672] Core::BasePath = D:\YARRR\BONELAB
[18:51:21.672] Game::BasePath = D:\YARRR\BONELAB
[18:51:21.672] Game::DataPath = D:\YARRR\BONELAB\BONELAB_Steam_Windows64_Data
[18:51:21.673] Game::ApplicationPath = D:\YARRR\BONELAB\BONELAB_Steam_Windows64.exe
[18:51:21.673] Runtime Type: net6
[18:51:21.756] ------------------------------
[18:51:21.756] Game Name: BONELAB
[18:51:21.757] Game Developer: Stress Level Zero
[18:51:21.758] Unity Version: 2021.3.5f1
[18:51:21.758] Game Version: 1.270.34555
[18:51:21.758] ------------------------------

[18:51:22.348] Preferences Loaded!

[18:51:22.472] Loading UserLibss from 'D:\YARRR\BONELAB\UserLibs'...

[18:51:22.480] Loading Plugins from 'D:\YARRR\BONELAB\Plugins'...
[18:51:22.480] ------------------------------
[18:51:22.484] Melon Assembly loaded: '.\Plugins\BoneLibUpdater.dll'
[18:51:22.485] SHA256 Hash: '325e9455cb6b586f3f9f58e68b5650bd650f7728d2dd04ee616f2fd3499d0e13'
[18:51:22.486] Melon Assembly loaded: '.\Plugins\LabFusionUpdater.dll'
[18:51:22.486] SHA256 Hash: '6460d1668189ba61b36e610bffafecca3c9494bf6d7f7f0d12a841ec9d45de60'

[18:51:22.516] ------------------------------
[18:51:22.516] BoneLibUpdater v1.1.1
[18:51:22.516] by Gnonme
[18:51:22.517] Assembly: BoneLibUpdater.dll
[18:51:22.517] ------------------------------
[18:51:22.520] ------------------------------
[18:51:22.520] LabFusion Updater v1.0.0
[18:51:22.520] by Lakatrazz
[18:51:22.520] Assembly: LabFusionUpdater.dll
[18:51:22.521] ------------------------------
[18:51:22.521] ------------------------------
[18:51:22.521] 2 Plugins loaded.
[18:51:22.542] [BoneLibUpdater] BoneLib is in ONLINE mode
[18:51:22.543] [BoneLibUpdater] BoneLib.dll found in Mods folder. Version: 3.1.0
[18:51:23.990] [BoneLibUpdater] BoneLib.dll updated successfully!
[18:51:23.991] [LabFusion_Updater] Fusion Auto-Updater is ONLINE.
[18:51:23.992] [LabFusion_Updater] LabFusion.dll found in Mods folder. Version: 1.8.0
[18:51:24.726] [LabFusion_Updater] LabFusion.dll is already up to date.
[18:51:25.778] [MelonStartScreen] Initializing...
[18:51:25.797] [MelonStartScreen] Using Start Screen Theme: "Default"
[18:51:26.654] Loading Il2CppAssemblyGenerator...
[18:51:26.668] [Il2CppAssemblyGenerator] Contacting RemoteAPI...
[18:51:26.858] [Il2CppAssemblyGenerator] Game Not Found on RemoteAPI Host (https://api.melonloader.com/api/v1/game/bonelab)
[18:51:26.861] [Il2CppAssemblyGenerator] RemoteAPI.DumperVersion = null
[18:51:26.861] [Il2CppAssemblyGenerator] RemoteAPI.ObfuscationRegex = null
[18:51:26.861] [Il2CppAssemblyGenerator] RemoteAPI.MappingURL = null
[18:51:26.862] [Il2CppAssemblyGenerator] RemoteAPI.MappingFileSHA512 = null
[18:51:26.867] [Il2CppAssemblyGenerator] Using Dumper Version: 2022.1.0-pre-release.15
[18:51:26.867] [Il2CppAssemblyGenerator] Using Il2CppInterop Version = 1.4.6-ci.433+45e22c2cb80a9586114a1815d77cc20104fd896c
[18:51:26.867] [Il2CppAssemblyGenerator] Using Unity Dependencies Version = 2021.3.5
[18:51:26.868] [Il2CppAssemblyGenerator] Using Deobfuscation Regex = null
[18:51:26.868] [Il2CppAssemblyGenerator] Cpp2IL is up to date.
[18:51:26.869] [Il2CppAssemblyGenerator] UnityDependencies is up to date.
[18:51:26.869] [Il2CppAssemblyGenerator] Checking GameAssembly...
[18:51:27.038] [Il2CppAssemblyGenerator] Assembly is up to date. No Generation Needed.

[18:51:27.045] Loading Mods from 'D:\YARRR\BONELAB\Mods'...
[18:51:27.045] ------------------------------
[18:51:27.075] Melon Assembly loaded: '.\Mods\BoneLib.dll'
[18:51:27.075] SHA256 Hash: '302235c57295a1aed3ddd6079d01f535f2de06fc0e161f90e6d1c137cb23774e'
[18:51:27.120] Melon Assembly loaded: '.\Mods\LabFusion.dll'
[18:51:27.120] SHA256 Hash: '1fd2ffc589823a0efb253c49f6bd3eb5bd09428b5ae9c20213e9d8ecec294a52'

[18:51:27.409] Some Melons are missing dependencies, which you may have to install.
If these are optional dependencies, mark them as optional using the MelonOptionalDependencies attribute.
This warning will turn into an error and Melons with missing dependencies will not be loaded in the next version of MelonLoader.
- 'LabFusion' is missing the following dependencies:
    - 'Il2CppSLZ.Marrow.VoidLogic.Core' v0.0.0.0
[18:51:27.414] ------------------------------
[18:51:27.414] BoneLib v3.1.0
[18:51:27.414] by The BONELAB Modding Community
[18:51:27.414] Assembly: BoneLib.dll
[18:51:27.415] ------------------------------
[18:51:27.425] [LabFusion] Data is at C:/Users/Hops/AppData/LocalLow/Stress Level Zero/BONELAB/Fusion/.
[18:51:27.425] [LabFusion] steam_api64.dll already exists, skipping extraction.
[18:51:27.426] [LabFusion] Successfully loaded steam_api64.dll into the application!
[18:51:27.427] Failed to register Mod 'D:\YARRR\BONELAB\Mods\LabFusion.dll': Melon failed to initialize!
[18:51:27.428] System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.RigManager' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at LabFusion.SDK.Points.PointItemManager.HookEvents()
   at LabFusion.FusionMod.OnEarlyInitializeMelon()
   at MelonLoader.MelonBase.Register() in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\MelonBase.cs:line 397
[18:51:27.428] ------------------------------
[18:51:27.428] 1 Mod loaded.

[18:51:27.932] Class::Init signatures have been exhausted, using a substitute!
[18:51:28.027] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[18:51:28.062] Registered mono type MelonLoader.Support.MonoEnumeratorWrapper in il2cpp domain
[18:51:28.064] Registered mono type MelonLoader.Support.SM_Component in il2cpp domain
[18:51:28.073] Support Module Loaded: D:\YARRR\BONELAB\MelonLoader\Dependencies\SupportModules\Il2Cpp.dll
[18:51:28.088] Method Void DrawHeader(BoneLib.BoneMenu.Page) on type BoneLib.BoneMenu.UI.GUIMenu has unsupported parameter BoneLib.BoneMenu.Page page of type BoneLib.BoneMenu.Page
[18:51:28.089] Method Void DrawBackground(BoneLib.BoneMenu.Page) on type BoneLib.BoneMenu.UI.GUIMenu has unsupported parameter BoneLib.BoneMenu.Page page of type BoneLib.BoneMenu.Page
[18:51:28.090] Method Void DrawFooter(BoneLib.BoneMenu.Page) on type BoneLib.BoneMenu.UI.GUIMenu has unsupported parameter BoneLib.BoneMenu.Page page of type BoneLib.BoneMenu.Page
[18:51:28.090] Method Void DrawElements(BoneLib.BoneMenu.Page) on type BoneLib.BoneMenu.UI.GUIMenu has unsupported parameter BoneLib.BoneMenu.Page page of type BoneLib.BoneMenu.Page
[18:51:28.131] Failed to load all types in assembly LabFusion, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null due to: Unable to load one or more of the requested types.
Could not load type 'ConstraintMode' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Interaction.Handedness' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Interaction.Handedness' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Interaction.Handedness' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Interaction.Handedness' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Interaction.Handedness' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'ConstraintMode' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'ConstraintMode' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'BodyPart' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'MeasurementState' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Grip' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Gun' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.InteractableHost' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.InventorySlotReceiver' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Interaction.KeyReceiver' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.ObjectDestructible' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Seat' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Bonelab.SimpleGripEvents' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.AI.AIBrain' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.AmmoSocket' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Atv' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Constrainer' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.FlyingGun' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.InventoryAmmoReceiver' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Magazine' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Pool.Poolee' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Bonelab.PropFlashlight' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.PuppetMasta.PuppetMaster' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Bonelab.SpawnGun' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.AI.TriggerRefProxy' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.WeaponSlot' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'GesturePose' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Warehouse.Crate' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Interaction.Handedness' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Interaction.Handedness' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'ConstraintMode' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Interaction.Handedness' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Interaction.Handedness' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Interaction.Handedness' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Interaction.Handedness' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Interaction.Handedness' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'ConstraintMode' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'ConstraintMode' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'BodyPart' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'MeasurementState' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Grip' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Gun' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.InteractableHost' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.InventorySlotReceiver' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Interaction.KeyReceiver' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.ObjectDestructible' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Seat' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Bonelab.SimpleGripEvents' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.AI.AIBrain' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.AmmoSocket' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Atv' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Constrainer' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.FlyingGun' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.InventoryAmmoReceiver' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Magazine' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Pool.Poolee' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Bonelab.PropFlashlight' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.PuppetMasta.PuppetMaster' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Bonelab.SpawnGun' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.AI.TriggerRefProxy' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.WeaponSlot' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'GesturePose' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Warehouse.Crate' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Interaction.Handedness' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Il2CppSLZ.Marrow.Interaction.Handedness' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at MelonLoader.MelonUtils.GetValidTypes(Assembly asm, LemonFunc`2 predicate) in D:\a\MelonLoader\MelonLoader\MelonLoader\MelonUtils.cs:line 258
System.TypeLoadException: Could not load type 'ConstraintMode' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.Interaction.Handedness' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.Interaction.Handedness' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.Interaction.Handedness' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.Interaction.Handedness' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.Interaction.Handedness' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'ConstraintMode' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'ConstraintMode' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'BodyPart' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'MeasurementState' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.Grip' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.Gun' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.InteractableHost' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.InventorySlotReceiver' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Interaction.KeyReceiver' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.ObjectDestructible' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.Seat' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Bonelab.SimpleGripEvents' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.AI.AIBrain' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.AmmoSocket' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.Atv' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.Constrainer' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.FlyingGun' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.InventoryAmmoReceiver' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.Magazine' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.Pool.Poolee' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Bonelab.PropFlashlight' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.PuppetMasta.PuppetMaster' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Bonelab.SpawnGun' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.AI.TriggerRefProxy' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.WeaponSlot' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'GesturePose' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.Warehouse.Crate' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.Interaction.Handedness' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.Interaction.Handedness' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by Lakatrazz** [comment]
Fusion does not support pirated copies.

**Comment by Killian1967** [comment]
it worked for months why all the sudden does it not support it now?

**Comment by Lakatrazz** [comment]
It's never supported it. You can try to get it to work on your own but you will not receive help as it can bring issues that are not fixable
