### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by frozdbyte** [Lakatrazz/BONELAB-Fusion#19]
The game crashes upon loading.

Using Oculus PCVR with public_beta channel and newest Melon Loader

Relevant logs:
```
[18:50:30.881] Some Melons are missing dependencies, which you may have to install.
If these are optional dependencies, mark them as optional using the MelonOptionalDependencies attribute.
This warning will turn into an error and Melons with missing dependencies will not be loaded in the next version of MelonLoader.
- 'BoneLib' is missing the following dependencies:
    - 'SLZ.Marrow' v0.0.0.0
    - 'SLZ.Marrow.SDK' v0.0.0.0
    - 'UnhollowerBaseLib' v0.4.18.0
    - 'UniTask' v0.0.0.0
- 'LabFusion' is missing the following dependencies:
    - 'SLZ.Marrow' v0.0.0.0
    - 'SLZ.Marrow.SDK' v0.0.0.0
    - 'UnhollowerBaseLib' v0.4.18.0
    - 'UltEvents' v1.0.0.0
    - 'UniTask' v0.0.0.0
[18:50:30.896] ------------------------------
[18:50:30.900] BoneLib v2.2.1
[18:50:30.900] by Gnonme
[18:50:30.906] Assembly: BoneLib.dll
[18:50:30.907] ------------------------------
[18:50:30.927] [LabFusion] Data is at C:/Users/USER/AppData/LocalLow/Stress Level Zero/BONELAB/Fusion/.
[18:50:30.928] [LabFusion] Loading embedded resource data LabFusion.Core.resources.lib.x86_64.steam_api64.dll...
[18:50:30.929] [LabFusion] Done!
[18:50:31.037] [LabFusion] Successfully loaded steam_api64.dll into the application!
[18:50:31.040] Failed to register Mod 'F:\OculusGames\Software\stress-level-zero-inc-bonelab\Mods\LabFusion.dll': Melon failed to initialize!
[18:50:31.042] System.TypeLoadException: Could not load type 'SLZ.Rig.RigManager' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Delegate.GetMulticastInvoke()
   at System.MulticastDelegate.CombineImpl(Delegate follow)
   at LabFusion.Utilities.MultiplayerHooking.add_OnLocalPlayerCreated(RigManagerEvent value)
   at LabFusion.Utilities.PlayerAdditionsHelper.OnInitializeMelon()
   at LabFusion.FusionMod.OnEarlyInitializeMelon()
   at MelonLoader.MelonBase.Register() in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\MelonBase.cs:line 397
[18:50:31.043] ------------------------------
[18:50:31.044] 1 Mod loaded.
```

**Comment by frozdbyte** [comment]
Turns out this was because I forgot to install Melon Loader using the provided Zip file for MelonLoader.
