### ISSUE TITLE
The fusion terminals/kiosks are missing and I can't spawn items after making a server.

### ISSUE THREAD

**Issue by Wild-Dog** [Lakatrazz/BONELAB-Fusion#93]
I tried removing every mod besides the ones to install fusion. I also get this error in melonloader.

[18:06:16.256] [LabFusion] Failed executing OnMainSceneInitialized hook with reason: Method not found: 'Il2CppCysharp.Threading.Tasks.UniTask`1<Il2CppSLZ.Marrow.Pool.Poolee> Il2CppSLZ.Marrow.Pool.AssetSpawner.SpawnAsync(Il2CppSLZ.Marrow.Data.Spawnable, UnityEngine.Vector3, UnityEngine.Quaternion, Il2CppSystem.Nullable`1<UnityEngine.Vector3>, UnityEngine.Transform, Boolean, Il2CppSystem.Nullable`1<Int32>, Il2CppSystem.Action`1<UnityEngine.GameObject>, Il2CppSystem.Action`1<UnityEngine.GameObject>)'.
Trace:   at LabFusion.Marrow.SafeAssetSpawner.Spawn(Spawnable spawnable, Vector3 position, Quaternion rotation, Action`1 spawnCallback)
   at LabFusion.SDK.Points.PointShopHelper.SpawnBitMart(Vector3 position, Quaternion rotation)
   at LabFusion.Data.VoidG114Data.MainSceneInitialized()
   at LabFusion.Data.LevelDataHandler.OnMainSceneInitialized()

**Comment by AdrianStillPlays** [comment]
Fusion is broken

**Comment by Wild-Dog** [comment]
> Fusion is broken

Okay. I'm also on patch 5, and so is a friend for whom it seems to work.

**Comment by Lakatrazz** [comment]
You aren't on patch 5, those errors are from patch 6, your game likely updated to patch 6 without you realizing. Fusion does not work on patch 6, please wait for the next update

**Comment by Wild-Dog** [comment]
Just to check, is update 1.1403.57485 patch 6? It's the LIVE version.

**Comment by Lakatrazz** [comment]
Yes, the live version is patch 6
